name: First github Docker CI Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout
    - name: Build container
      run: docker build -t real-devops-lab-app .
